#ifndef RC_CAR_FIRMWARE_FRONTEND_H
#define RC_CAR_FIRMWARE_FRONTEND_H

const char GLOBAL_FRONTEND[] = "<!doctype html>\n"
                               "<html>\n"
                               "\n"
                               "<head>\n"
                               "  <meta name=\"viewport\"\n"
                               "        content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\">\n"
                               "  <style>\n"
                               "    .container{\n"
                               "      width: 100%;\n"
                               "      height: 100%;\n"
                               "      display: flex;\n"
                               "      align-items: center;\n"
                               "      justify-content: center;\n"
                               "      gap: 20px;\n"
                               "    }\n"
                               "    .title{\n"
                               "      display: block;\n"
                               "      font-size: 24px;\n"
                               "      width: 100%;\n"
                               "      text-align: center;\n"
                               "      margin-top: 5px;\n"
                               "      margin-bottom: 5px;\n"
                               "    }\n"
                               "    html, body {margin: 0; height: 100%; overflow: hidden}\n"
                               "    .controll-pannel{\n"
                               "      width: 100%;\n"
                               "      flex-grow: 100;\n"
                               "      max-height: 300px;\n"
                               "      max-width: 300px;\n"
                               "      display: flex;\n"
                               "      flex-direction: column;\n"
                               "      div{\n"
                               "        display: flex;\n"
                               "        justify-content: space-around;\n"
                               "      }\n"
                               "      div:nth-child(2){\n"
                               "        justify-content: space-between;\n"
                               "      }\n"
                               "      button{\n"
                               "        border: #555555;\n"
                               "        width: 100px;\n"
                               "        height: 100px;\n"
                               "        padding: 5px;\n"
                               "        img{\n"
                               "          max-width: 100%;\n"
                               "          max-height: 100%;\n"
                               "          user-select: none;\n"
                               "          -moz-user-select: none;\n"
                               "          -khtml-user-select: none;\n"
                               "          -webkit-user-select: none;\n"
                               "          -o-user-select: none;\n"
                               "          pointer-events: none;\n"
                               "          user-drag: none;\n"
                               "        }\n"
                               "        svg{\n"
                               "          max-width: 100%;\n"
                               "          max-height: 100%;\n"
                               "          user-select: none;\n"
                               "          -moz-user-select: none;\n"
                               "          -khtml-user-select: none;\n"
                               "          -webkit-user-select: none;\n"
                               "          -o-user-select: none;\n"
                               "          pointer-events: none;\n"
                               "          user-drag: none;\n"
                               "        }\n"
                               "      }\n"
                               "      button:active{\n"
                               "        background: #222222;\n"
                               "      }\n"
                               "      #left-button{\n"
                               "        transform: rotateZ(0deg);\n"
                               "      }\n"
                               "      #right-button{\n"
                               "        transform: rotateZ(180deg);\n"
                               "      }\n"
                               "      #up-button{\n"
                               "        transform: rotateZ(90deg);\n"
                               "      }\n"
                               "      #down-button{\n"
                               "        transform: rotateZ(270deg);\n"
                               "      }\n"
                               "    }\n"
                               "    .stream{\n"
                               "      width: 300px;\n"
                               "      height: 200px;\n"
                               "      background: black;\n"
                               "      margin: auto;\n"
                               "    }\n"
                               "\n"
                               "    @media screen and (orientation:portrait) {\n"
                               "      .container{\n"
                               "        flex-direction: column;\n"
                               "      }\n"
                               "    }\n"
                               "\n"
                               "    @media screen and (orientation:landscape) {\n"
                               "      .container{\n"
                               "        flex-direction: row;\n"
                               "      }\n"
                               "      .stream{\n"
                               "        width: 400px;\n"
                               "        height: 266px;\n"
                               "        background: black;\n"
                               "        margin: auto;\n"
                               "      }\n"
                               "    }\n"
                               "\n"
                               "  </style>\n"
                               "\n"
                               "  <script>\n"
                               "    class OnHold{\n"
                               "      constructor(target, callback) {\n"
                               "        this.target = target;\n"
                               "        this.callback = callback;\n"
                               "        this.isHolding = false;\n"
                               "        this.activeHoldTimeoutId = null;\n"
                               "\n"
                               "        [\"mousedown\", \"touchstart\"].forEach((type)=>{\n"
                               "          this.target.addEventListener(type, this._onHoldStart.bind(this))\n"
                               "        });\n"
                               "        [\"mouseup\", \"mouseleave\", \"mouseout\", \"touchend\", \"touchcancel\"].forEach((type)=>{\n"
                               "          this.target.addEventListener(type, this._onHoldEnd.bind(this))\n"
                               "        })\n"
                               "      }\n"
                               "\n"
                               "        _onHoldStart(){\n"
                               "          if (!this.isHolding)\n"
                               "              this.callback()\n"
                               "          this.isHolding = true;\n"
                               "          this.activeHoldTimeoutId = setInterval(() => {\n"
                               "            if (this.isHolding) {\n"
                               "              this.callback();\n"
                               "            }\n"
                               "          }, 100)\n"
                               "        }\n"
                               "\n"
                               "      _onHoldEnd(){\n"
                               "        this.isHolding = false;\n"
                               "        clearInterval(this.activeHoldTimeoutId);\n"
                               "      }\n"
                               "\n"
                               "    }\n"
                               "  </script>\n"
                               "</head>\n"
                               "\n"
                               "<body>\n"
                               "  <div class=\"container\">\n"
                               "    <div>\n"
                               "    <span class=\"title\">This is Control panel for RC Car!</span>\n"
                               "<!--      <div class=\"stream\">-->\n"
                               "\n"
                               "<!--      </div>-->\n"
                               "    </div>\n"
                               "    <div class=\"controll-pannel\">\n"
                               "      <div>\n"
                               "        <button id=\"up-button\"><?xml version=\"1.0\" encoding=\"utf-8\"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n"
                               "          <svg width=\"800px\" height=\"800px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
                               "            <path d=\"M13.9783 5.31877L10.7683 8.52877L8.79828 10.4888C7.96828 11.3188 7.96828 12.6688 8.79828 13.4988L13.9783 18.6788C14.6583 19.3588 15.8183 18.8688 15.8183 17.9188V12.3088V6.07877C15.8183 5.11877 14.6583 4.63877 13.9783 5.31877Z\" fill=\"#292D32\"/>\n"
                               "          </svg></button>\n"
                               "      </div>\n"
                               "      <div>\n"
                               "        <button id=\"left-button\"><?xml version=\"1.0\" encoding=\"utf-8\"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n"
                               "          <svg width=\"800px\" height=\"800px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
                               "            <path d=\"M13.9783 5.31877L10.7683 8.52877L8.79828 10.4888C7.96828 11.3188 7.96828 12.6688 8.79828 13.4988L13.9783 18.6788C14.6583 19.3588 15.8183 18.8688 15.8183 17.9188V12.3088V6.07877C15.8183 5.11877 14.6583 4.63877 13.9783 5.31877Z\" fill=\"#292D32\"/>\n"
                               "          </svg></button>\n"
                               "        <button id=\"right-button\"><?xml version=\"1.0\" encoding=\"utf-8\"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n"
                               "          <svg width=\"800px\" height=\"800px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
                               "            <path d=\"M13.9783 5.31877L10.7683 8.52877L8.79828 10.4888C7.96828 11.3188 7.96828 12.6688 8.79828 13.4988L13.9783 18.6788C14.6583 19.3588 15.8183 18.8688 15.8183 17.9188V12.3088V6.07877C15.8183 5.11877 14.6583 4.63877 13.9783 5.31877Z\" fill=\"#292D32\"/>\n"
                               "          </svg></button>\n"
                               "      </div>\n"
                               "      <div>\n"
                               "        <button id=\"down-button\"><?xml version=\"1.0\" encoding=\"utf-8\"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n"
                               "          <svg width=\"800px\" height=\"800px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
                               "            <path d=\"M13.9783 5.31877L10.7683 8.52877L8.79828 10.4888C7.96828 11.3188 7.96828 12.6688 8.79828 13.4988L13.9783 18.6788C14.6583 19.3588 15.8183 18.8688 15.8183 17.9188V12.3088V6.07877C15.8183 5.11877 14.6583 4.63877 13.9783 5.31877Z\" fill=\"#292D32\"/>\n"
                               "          </svg></button>\n"
                               "      </div>\n"
                               "    </div>\n"
                               "  </div>\n"
                               "\n"
                               "  <script>\n"
                               "    let commandBuffer = [];\n"
                               "    const click = (command) => (() => {\n"
                               "      // console.log(command);\n"
                               "      commandBuffer.push(command);\n"
                               "    })\n"
                               "    const clickUp = async () => click(\"U\")();\n"
                               "    const clickDown = async () => click(\"D\")();\n"
                               "    const clickRight = async () => click(\"R\")();\n"
                               "    const clickLeft = async () => click(\"L\")();\n"
                               "\n"
                               "    new OnHold(document.getElementById(\"up-button\"), clickUp)\n"
                               "    new OnHold(document.getElementById(\"down-button\"), clickDown)\n"
                               "    new OnHold(document.getElementById(\"left-button\"), clickLeft)\n"
                               "    new OnHold(document.getElementById(\"right-button\"), clickRight)\n"
                               "\n"
                               "    let socket = new WebSocket('ws://192.168.4.1/ws');\n"
                               "\n"
                               "    const sendToServer = (data) => {\n"
                               "      data = data.substring(0, 15);\n"
                               "      console.log(\"sent to server\", data);\n"
                               "      if (data.length > 0){\n"
                               "        if (socket.readyState === WebSocket.OPEN) {\n"
                               "          socket.send(data); // Send data if the socket connection is open\n"
                               "        } else {\n"
                               "          console.error('WebSocket connection is not open');\n"
                               "        }\n"
                               "      }\n"
                               "    }\n"
                               "\n"
                               "    setInterval(()=>{\n"
                               "      const commandString = commandBuffer.reduce((string, symbol) => string + symbol, \"\");\n"
                               "      sendToServer(commandString);\n"
                               "      commandBuffer = [];\n"
                               "    }, 100)\n"
                               "  </script>\n"
                               "\n"
                               "</body>\n"
                               "\n"
                               "</html>";

#endif //RC_CAR_FIRMWARE_FRONTEND_H
